//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolhaPagamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string cpf { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string cep { get; set; }
        public string logradouro { get; set; }
        public string bairro { get; set; }
        public string estado { get; set; }
        public string numero { get; set; }
        public string cidade { get; set; }
    }
}
